/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as GeneratingRouteImport } from './routes/generating'
import { Route as DeadlinesRouteImport } from './routes/deadlines'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CityRouteImport } from './routes/city'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuildingIdRouteImport } from './routes/building.$id'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratingRoute = GeneratingRouteImport.update({
  id: '/generating',
  path: '/generating',
  getParentRoute: () => rootRouteImport,
} as any)
const DeadlinesRoute = DeadlinesRouteImport.update({
  id: '/deadlines',
  path: '/deadlines',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CityRoute = CityRouteImport.update({
  id: '/city',
  path: '/city',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingIdRoute = BuildingIdRouteImport.update({
  id: '/building/$id',
  path: '/building/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/city': typeof CityRoute
  '/dashboard': typeof DashboardRoute
  '/deadlines': typeof DeadlinesRoute
  '/generating': typeof GeneratingRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/building/$id': typeof BuildingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/city': typeof CityRoute
  '/dashboard': typeof DashboardRoute
  '/deadlines': typeof DeadlinesRoute
  '/generating': typeof GeneratingRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/building/$id': typeof BuildingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/city': typeof CityRoute
  '/dashboard': typeof DashboardRoute
  '/deadlines': typeof DeadlinesRoute
  '/generating': typeof GeneratingRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/building/$id': typeof BuildingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/city'
    | '/dashboard'
    | '/deadlines'
    | '/generating'
    | '/onboarding'
    | '/profile'
    | '/building/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/city'
    | '/dashboard'
    | '/deadlines'
    | '/generating'
    | '/onboarding'
    | '/profile'
    | '/building/$id'
  id:
    | '__root__'
    | '/'
    | '/city'
    | '/dashboard'
    | '/deadlines'
    | '/generating'
    | '/onboarding'
    | '/profile'
    | '/building/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CityRoute: typeof CityRoute
  DashboardRoute: typeof DashboardRoute
  DeadlinesRoute: typeof DeadlinesRoute
  GeneratingRoute: typeof GeneratingRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  BuildingIdRoute: typeof BuildingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generating': {
      id: '/generating'
      path: '/generating'
      fullPath: '/generating'
      preLoaderRoute: typeof GeneratingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deadlines': {
      id: '/deadlines'
      path: '/deadlines'
      fullPath: '/deadlines'
      preLoaderRoute: typeof DeadlinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city': {
      id: '/city'
      path: '/city'
      fullPath: '/city'
      preLoaderRoute: typeof CityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/building/$id': {
      id: '/building/$id'
      path: '/building/$id'
      fullPath: '/building/$id'
      preLoaderRoute: typeof BuildingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CityRoute: CityRoute,
  DashboardRoute: DashboardRoute,
  DeadlinesRoute: DeadlinesRoute,
  GeneratingRoute: GeneratingRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  BuildingIdRoute: BuildingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
