FROM python:3.11-slim

WORKDIR /app

COPY requirements_fastapi.txt .
RUN pip install --no-cache-dir -r requirements_fastapi.txt

COPY . .

EXPOSE 8080
CMD ["uvicorn", "bank_recommendation_service:app", "--host", "0.0.0.0", "--port", "8080"]